export const FETCH_LOGIN_DETAILS = 'FETCH_LOGIN_DETAILS';
export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS', 
    GETALL_FAILURE: 'USERS_GETALL_FAILURE', 

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
}; 

export const alertConstants = { 
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const FETCH_PROJECT_ACTION = 'FETCH_PROJECT_ACTION';
export const FETCH_COMP_ACTION = 'FETCH_COMP_ACTION';
export const OPEN_INSIDE_DRAWER = 'OPEN_INSIDE_DRAWER';
export const CLOSE_INSDE_DRAWER = 'CLOSE_INSDE_DRAWER';
export const GET_USER_DATA = 'GET_USER_DATA';
